### ISSUE TITLE
[BUG] stopped working 

### ISSUE THREAD

**Issue by Rogal80** [Zuellni/stable-diffusion-webui-image-filters#1]
hi, after latest update, always same issue in the cmd 
![image](https://user-images.githubusercontent.com/112553453/224823491-6f3549ec-56f4-4690-be4a-b7ced4317b79.png)

on this revision 02c6d78c is still working

**Comment by Zuellni** [comment]
I don't see any errors in your screenshot nor can I reproduce on my end. Is the issue that the generation is pausing before/after saving while the extension is enabled?

Did you try removing the lines starting with `customscript/image_filters.py` in your `ui-config.json` as per the readme notes? Some values might be cached incorrectly. If that doesn't help, what effects or filters do you have enabled and does it happen for every single image or batches/hires fix?

**Comment by Rogal80** [comment]
Hi, removing all lines with image filters from config – resolved the issue, thank you
